apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "idp.fullname" . }}-config
  labels:
    {{- include "idp.labels" . | nindent 4 }}
data:
  appsettings.{{ .Values.environment }}.json: |
    {
      "Serilog": {
        "MinimumLevel": {
          "Default": "{{ .Values.logLevel }}"
        }
      },
      "DataProtection": {
        "CertificatePath": "{{ .Values.dataProtection.certificatePath }}",
        "StorageMode": "DbContext"
      },
      "Hydra": {
        "AdminApi": {
          "Url": "{{ .Values.hydra.adminApi.url }}",
          "BypassCertificateValidation": {{ .Values.hydra.adminApi.bypassCertificateValidation }}
        },
        "PublicApi": {
          "Url": "{{ .Values.hydra.publicApi.url }}",
          "BypassCertificateValidation": {{ .Values.hydra.publicApi.bypassCertificateValidation }}
        }
      },
      "Users": {
        "Clients": {
          {{- if .Values.grpc.ldap.enabled }}
          "ldap": {
            "Address": "{{ .Values.grpc.ldap.address }}",
            "CertificatePath": "/etc/ssl/certs/grpc-ldap-tls.crt"
          }
          {{- end }}
          {{- if and .Values.grpc.ldap.enabled .Values.grpc.accounts.enabled }}
          ,
          {{- end }}
          {{- if .Values.grpc.accounts.enabled }}
          "accounts": {
            "Address": "{{ .Values.grpc.accounts.address }}",
            "CertificatePath": "/etc/ssl/certs/grpc-accounts-tls.crt"
          }
          {{- end }}
        }
      }
    }
